name: Checkov Scan
on: [push]

variables:
- name: checks_to_skip
  value: CKV_AWS_42 


# Checkov_Checks_To-Skip:
#   CHECKOV_CHECKS_TO_SKIP: "CKV_AWS_42"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory : .deploy/terraform
          skip_check: {{ variables.checks_to_skip }}
          # soft_fail : false
          # quiet     : false
          framework : terraform 
